apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-mysql
  labels:
    app: app-mysql
    tier: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app: app-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password        
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts: 
        - name: mysql-persistent-storage
          mountPath: var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-service
spec:
  ports:
    - port: 3306
  selector:
    app: app-mysql
    tier: mysql
  clusterIP: None